# Generated by Django 2.0.3 on 2018-05-28 17:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalData', models.CharField(blank=True, max_length=1000, verbose_name='Personal data')),
                ('experience', models.CharField(blank=True, max_length=300, verbose_name='Experience')),
                ('education', models.CharField(blank=True, max_length=100, verbose_name='Education')),
                ('misc', models.CharField(blank=True, max_length=300, verbose_name='Miscellaneous')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Rate')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal code')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
                ('avaliability', models.BooleanField(default=1)),
                ('category', models.CharField(choices=[('Cuidado parcial', 'Cuidado parcial'), ('Cuidado completo', 'Cuidado completo'), ('Cuidado nocturno', 'Cuidado nocturno'), ('Cuidado hospitalario', 'Cuidado hospitalario'), ('Recados', 'Recados'), ('Sin especificar', 'Sin especificar')], max_length=50, verbose_name='Category')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('feedback', models.ManyToManyField(to='principal.Feedback')),
                ('offerer', models.ManyToManyField(blank=True, related_name='offerer', to=settings.AUTH_USER_MODEL, verbose_name='Offerers')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="El número debe seguir el siguiente patrón: '+999999999'. Máximo 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone')),
                ('postalAddress', models.CharField(max_length=100, verbose_name='Postal address')),
                ('gender', models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre'), ('O', 'Otro')], max_length=1, verbose_name='Gender')),
                ('occupation', models.CharField(max_length=100, verbose_name='Occupation')),
                ('photo', models.URLField(max_length=600, verbose_name='Photo')),
                ('socialReferences', models.CharField(blank=True, max_length=600, null=True, verbose_name='Social references')),
                ('dni', models.CharField(max_length=9)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
