# Generated by Django 2.0.3 on 2018-04-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='ranking',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Ranking'),
        ),
        migrations.RemoveField(
            model_name='service',
            name='feedback',
        ),
        migrations.AddField(
            model_name='service',
            name='feedback',
            field=models.ManyToManyField(to='principal.Feedback'),
        ),
    ]
