# Generated by Django 2.0.3 on 2018-04-10 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='offerer',
            field=models.ManyToManyField(blank=True, related_name='offerer', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
    ]
